### ISSUE TITLE
importing py_sg error

### ISSUE THREAD

**Issue by sulphuricacid** [0-duke/wdpassport-utils#10]
my pip3 list shows the py_sg package as present but when im running the command im getting error as you need to install py_sg package

**Comment by giappi** [comment]
@sulphuricacid 
Because py_sg not work on Python3. You use Python 2 instead.

**Comment by 7aman** [comment]
Hi.
Based on two projects of @crypto-universe I created an PyPi package compatible with python3.  
You need to install `python-dev` package of your official distribution. then:
```shell
sudo python3 -m pip install wdpass
# how to use
sudo wdpass --help
```

more info:
[wdpass](https://github.com/7aman/wdpass)

**Comment by tvladyslav** [comment]
@sulphuricacid you can use https://github.com/crypto-universe/py_sg , it is rewritten for Python3.

**Comment by 0-duke** [comment]
I've merged to master the version from @JoshData containing the "py_sg" for Python3 made by @crypto-universe. 
Thanks all guys, this is fixed now.
