### ISSUE TITLE
Version 0.2 Detailed Installation Procedure

### ISSUE THREAD

**Issue by www-MKRD-info** [0-duke/wdpassport-utils#13]
Folks,
Lots of devs are skimpy on detailed procedure and all prerequisites (mostly because they have all the prerequisites on their machine from a long ago), so here are ALL prerequisites and installation steps:

sudo apt install python3-dev
Python 3 is a prerequisite for this software.

sudo apt install python3-pip
Addresses error:
pip3: command not found

sudo apt install git
Addresses error:
No such file or directory: 'git'

sudo apt-get install python3-setuptools
Addresses error:
No module named 'setuptools'

pip3 install --user git+https://github.com/crypto-universe/py_sg
Addresses error:
You need to install the "py_sg" module.

Unfortunately, version 0.2 does not work with WD MyBook that has worked with version 0.1 so until we find out what is going on, keep using version 0.1...

**Comment by 0-duke** [comment]
Thanks www-MKRD-info. I've updated the instructions on the readme.
