### ISSUE TITLE
Version 0.2 does not work with WD MyBook that works with v0.1

### ISSUE THREAD

**Issue by www-MKRD-info** [0-duke/wdpassport-utils#14]
@0-duke,
RE: Some How-To tips #6 
It is nice to hear from you! I just assumed (from years of inactivity) that you are gone for good.
I have just installed version 0.2. Unfortunately, it does not work with a WD MyBook that has worked fine with version 0.1 of this software.

Version 0.1 autodetect never worked, so I always forced it as:
sudo ./wdpassport-utils.py -d /dev/sdc -u

Version 0.2 does not want to see me whether I force it or not. I tried both:
sudo wdpassport-utils.py -d /dev/sdc -u
and
sudo wdpassport-utils.py -u
In both cases I get the same message:
[!] No Western Digital Passport device found.

I am using WD MyBook USB 3.0 version. Part number is WDBBGB0060HBK-NA

**Comment by sirVir** [comment]
I made a small fix which made MyBook work for me:
#15

**Comment by 0-duke** [comment]
Thanks @sirVir for your investigation on this. I've modified master relaxing the device selection with the string "Western_Digital_My_" that will work for both My Passport and My Book. 

If it doesn't work please open a new issue.

**Comment by www-MKRD-info** [comment]
@0-duke, V0.2(2) confirmed to work with WD MyBook. It still does not understand a drive in sleep mode however, I will post that as a separate item.
