### ISSUE TITLE
Python3 version does not recognize my drive

### ISSUE THREAD

**Issue by XenHat** [0-duke/wdpassport-utils#17]
Similar to #14 
I have a device here that can be read (but not more more) at https://github.com/0-duke/wdpassport-utils/tree/0a251b2a3a647513c430efab7a1bb3a18fedd642:

```bash
sudo python2 ./wdpassport-utils.py -d /dev/sda -s
WD Passport Ultra linux utility v0.1 by duke
[*] Device state
	Security status: No keys
	Encryption type: unknown
```
but cannot be read with the python3 version:
```bash
 sudo ./wdpassport-utils.py -d /dev/sda 
[!] No Western Digital Passport device found.
```
The drive came here without a label for repair and doesn't have a standard SATA adapter (micro usb is soldered directly to the PCB (sigh...)). All I can currently say about it is that it is from Western Digital, and **Not For Resale** (P/N `WD10TMVV`)

**Comment by 0-duke** [comment]
Few observations:
1) this utility has been  developed and tested with WD Passport Ultra. It seems to support WD MyBook but I don't know if can be used with any other WD HD device without changing the code 
3) Can you open/mount the device with the official WD utility for Windows?

**Comment by XenHat** [comment]
> Few observations:
> 
>     1. this utility has been  developed and tested with WD Passport Ultra. It seems to support WD MyBook but I don't know if can be used with any other WD HD device without changing the code
> 
>     2. Can you open/mount the device with the official WD utility for Windows?

1. I do not know if this drive qualifies as a WD Passport, I found this repository by searching for the error message in `dmesg`.
![IMG_20200506_110400_1](https://user-images.githubusercontent.com/980408/81193494-7685e780-8f89-11ea-9567-68ebbd282f98.jpg)
![IMG_20200506_110418_1](https://user-images.githubusercontent.com/980408/81193513-7ab20500-8f89-11ea-87f5-08ec944279f7.jpg)


2. I will try and report.

**Comment by XenHat** [comment]
OK, the drive shows up as a `WD Elements 1023 USB Device` in Windows (`USBSTOR\DISK&VEN_WD&PROD_ELEMENTS_1023&REV_2005`).
Do I guess correctly that there is no way to get this drive working as  the WD Drive Utilities don't see it ("Attach a supported WD Drive") and I cannot mount it under either Windows or Linux?

**Comment by 0-duke** [comment]
Correct, if the drive doesn't work with the official utility there is nothing you can do with our wdpassport-utils. I'm closing this issue.
