### ISSUE TITLE
Scsi or USB?

### ISSUE THREAD

**Issue by ralhei** [0-duke/wdpassport-utils#19]
Hi guys,
this is probably a very stupid question, but I'm confused ;-) Your project uses a SCSI driver to communicate with the WD disk, so does this mean it NOT work with USB3 drives? I'm asking this because I'm intending to buy such a USB disk for my Linux box and I'm trying to find out which software helps me with the disk encryption on the Linux side. Any clarification is very much appreciated.
Ralph

**Comment by EagleScreen** [comment]
Linux kernel merged the usb and scsi driver years ago. So scsi, pata and
usb are using the same driver.

**Comment by ralhei** [comment]
Cool - thanks for your fast reply!
