### ISSUE TITLE
How to find HDD /dev/...

### ISSUE THREAD

**Issue by Ya-Boi-Hype** [0-duke/wdpassport-utils#20]
I've been spending the last 15 minutes trying to workaround my password encrypted My Passport on my Ubuntu Laptop and I can't find the discriminating letters of my HDD. I couldn't find anything on fdisk either and it's just showing up the virtual disc for the Windows unlocker. What do I do? Thanks.

**Comment by JoshData** [comment]
Running `dmesg` on the command line after plugging in the device should help.
