### ISSUE TITLE
Support for internal hard-drives?

### ISSUE THREAD

**Issue by beaugenereux** [0-duke/wdpassport-utils#23]
Hello!

I purchased a surveillance hard-drive (WDC WD10PURZ-85U8XY0) for my NVR kit and I am stuck: it is locked, cannot be formatted nor detected by the NVR kit. Furthermore, it is an internal hard-drive and I do not have access to Windows to run the official WD software. 

I am on Linux Mint (Cinnamon) so I tried to make Wine work with WD Security/Disk Utility software but it fails trying to install some .NET stuff.

Trying a different approach, I found your code. It is by far the closest I have been to a solution but the script simply tells me that: 

> [!] No Western Digital Passport device found.

Is there a way to modify this script so it can unlock an internal hard-drive?

Thanks in advance!

**Comment by 0-duke** [comment]
Hi beaugenereux,

the script is trying to autodetect a compatible device, checking if the ID of the device starts with the string "Western_Digital_My_". 
If that's not present the script will return the error you pointed out.

Unfortunately I have no idea if "WDC WD10PURZ-85U8XY0" is using the same encryption/decryption mechanism hence if it's compatible with this script.

What you can do - at your own risk - is to manually identify your device (as instance with "fdisk -l" or "lsblk --nodeps" commands) and then specify the device location with the argument "-d". 

Let's imagine your hard-disk is on "/dev/sdd" you will need to run the script as following: 

./wdpassport-utils.py -d /dev/sdd
