### ISSUE TITLE
Some How-To tips

### ISSUE THREAD

**Issue by www-MKRD-info** [0-duke/wdpassport-utils#6]
Duke,
There is no way to contact you that I can find. Please list some contact info.

I am not a very experienced Linux user, so I got the script to work eventually by following these steps:

1. I had to install py_sg by Googling for its online posting, grabbing the install file, and running the install file with -install option.
https://pypi.python.org/pypi/py_sg/

2. Users be aware that right-clicking of script file and choosing "Save link as..." DOES NOT download the actual file! You have to first view the script file, then click "Raw" button, and THEN downloading plaintext script contents to a file from the browser. This github behavior is a little stupid in my opinion. Otherwise you will download a file with script's filename but HTML code inside!!! (Check the contents of script file with any text editor).

3. Always use sudo with this command in the Terminal: Every time you run the script you have to type in
sudo ./wdpassport-utils.py (any commands here)
and enter your password.

4. The auto-detect option probably works for Passport drives only. It does not work for WD My Drive. In this case you have to use the -d or --device flag IN FRONT OF EVERY COMMAND YOU TYPE IN.
So for example, if autodetect does not work and you want to unlock, after you figure out the path to your drive, enter
sudo ./wdpassport-utils.py -d /dev/sde -u
First enter your username password, then you will be prompted for drive's password.
Of course for you "sde" will probably be something else.

5. Error when hard drive is in power save mode:
If the HD is currently in power save mode, the following extensive but non-intuitive error is shown:
"Traceback (most recent call last):
File "./wdpassport-utils.py", line 428, in
main(sys.argv[1:])
File "./wdpassport-utils.py", line 412, in main
unlock()
File "./wdpassport-utils.py", line 199, in unlock
iteration,salt,hint = read_handy_store_block1()
File "./wdpassport-utils.py", line 142, in read_handy_store_block1
sector_data = read_handy_store(1)
File "./wdpassport-utils.py", line 94, in read_handy_store
data = py_sg.read(dev, _scsi_pack_cdb(cdb), BLOCK_SIZE)
py_sg.SCSIError: (1, 0, 8, 'p\x00\x02\x00\x00\x00\x00\n\x00\x00\x00\x00\x04\x01\x00\x00\x00\x00')
"
AFTER the error is shown, the hard drive starts coming out of Power Save mode. Then, the utility has to be re-run with the password again to be able to unlock the HD.

Confirmed works! Thanks!
http://www.MKRD.info/

**Comment by 0-duke** [comment]
Hi @www-MKRD-info, apologies for the late reply. The latest version of the software should have fixed all of this. Better late than never :)

**Comment by www-MKRD-info** [comment]
@0-duke, 
Please see reply in https://github.com/0-duke/wdpassport-utils/issues/14
Version 0.2 does not work where 0.1 did.

**Comment by sirVir** [comment]
I made a small fix which made MyBook work for me:
https://github.com/0-duke/wdpassport-utils/pull/15
