### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ghost** [0-duke/wdpassport-utils#7]
Can you update the script for nowadays use? I'm new on python and I fixed some old-syntax errors that python complained about your script, but furthermore there's a problem with importing py-sg, I think it's because of version change on python 2.7 - 3. Besides, It cannot load (import) py-sg.

**Comment by 7aman** [comment]
@Neules 
Hi.
Based on two projects of @crypto-universe I created an PyPi package compatible with python3.  
You need to install `python-dev` package of your official distribution. then:
```shell
sudo python3 -m pip install wdpass
# how to use
sudo wdpass --help
```

more info:
[wdpass](https://github.com/7aman/wdpass)

**Comment by 0-duke** [comment]
I've merged the latest version from @JoshData. Now python3 is supported.
